_target_: src.models.deepmtlr_model.DEEP_MTLR


model: "UNETR"
dense_factor : 3 # Factor to multiply width of fc layer.  2
n_dense : 3      # Number of fc layers.  2
dropout : 0.25
C1 : 100  #Regularization term for MTLR backprop.
lr : 2e-3  # should be <= 2e-4,2e-4
weight_decay: 0.001  # 0.001
time_bins: 8
loss_gamma: 0.9

#CNN
k1 : 3
k2 : 5

step: 50

#ViT
patch_size : 8
hidden_size : 256 #768
mlp_dim : 1024
num_layers : 6
num_heads : 8